ALTER TABLE member ALTER COLUMN id RESTART WITH 1;
ALTER TABLE section ALTER COLUMN id RESTART WITH 1;
ALTER TABLE holdings ALTER COLUMN id RESTART WITH 1;
ALTER TABLE items_kr ALTER COLUMN id RESTART WITH 1;